version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    tty: true
    restart: always
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      # PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
